// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDT-2Yct5_acTaa-XpdcxuDsMK3cS22k',
    appId: '1:14684272223:web:90239e2a237414dd050dea',
    messagingSenderId: '14684272223',
    projectId: 'scrum-86279',
    authDomain: 'scrum-86279.firebaseapp.com',
    storageBucket: 'scrum-86279.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzdHbzihnXZbtSPwX4IRuaT5AJuwGMCI',
    appId: '1:14684272223:android:2e6f3bcc7cc1db00050dea',
    messagingSenderId: '14684272223',
    projectId: 'scrum-86279',
    storageBucket: 'scrum-86279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNspFWXD7lMrTEI-63hVBA8qOg2p4254',
    appId: '1:14684272223:ios:9045067dea90889e050dea',
    messagingSenderId: '14684272223',
    projectId: 'scrum-86279',
    storageBucket: 'scrum-86279.appspot.com',
    iosBundleId: 'com.example.projectEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfNspFWXD7lMrTEI-63hVBA8qOg2p4254',
    appId: '1:14684272223:ios:0a7e56775866f0e5050dea',
    messagingSenderId: '14684272223',
    projectId: 'scrum-86279',
    storageBucket: 'scrum-86279.appspot.com',
    iosBundleId: 'com.example.projectEnd.RunnerTests',
  );
}
